sudo: required
services:
  -docker

before_install:
  - docker build -t shenyiting2018/docker-react -f Dockerfile.dev .


scripts:
  - docker run shenyiting2018/docker-react npm run test -- --coverage
  #- docker run -e CI=true shenyiting2018/docker-react npm run test