sudo: required
services:
  - docker

before_install:
  - docker build -t shenyiting2018/docker-react -f Dockerfile.dev .


script:
  #- docker run shenyiting2018/docker-react npm run test -- --coverage
  - docker run -e CI=true shenyiting2018/docker-react npm run test


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-492743170678"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




#Docker-env.eba-vnmp3xgc.us-east-2.elasticbeanstalk.com